apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-v4
  labels:
    apps: java-app-v4
spec:
  selector:
    matchLabels:
      app: java-app-v4
  replicas: 2 
  template:
    metadata:
      labels:
        app: java-app-v4
    spec:
      containers:
      - name: java-app-v4
        image: csnkarthik/javaapp:latest 
        ports:
        - containerPort: 8080
